# Meta Data for SEO

## Homepage
title = "dhivehi.ai"
titleSeparator = "-"
titleAddition = "Dhivehi to for the next generation"
description = "A community effort to accelerate development of tech around Dhivehi"

## Open Graph + Twitter Cards
images = ["dhivehi.png"]
twitterSite = "dhivehiai"
twitterCreator = "dhivehiai"
facebookAuthor = "DhivehiAI"
facebookPublisher = "DhivehiAI"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "dhivehiai-logo.png"
schemaTwitter = "https://twitter.com/dhivehiai"
schemaGitHub = "https://github.com/DhivehiAI"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Made with <3 in Maldives"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/h-enk/doks"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
  highLight = true
  kaTex = false
